### PR TITLE
Fix the issue with the projects, finalize the network functionality by adding a new screen to people to your connections list. I also got rid of the connection array inside the user table and created a new table for that to make it easier to add connection. Created a card for the connection view and created a function to add connection to a user.

### PR DESCRIPTION
**Pull request by NatalmanNahm**

### CODE REVIEW

**Comment by NatalmanNahm** [comment]
Fix the issue with the projects, finalize the network functionality by adding a new screen to people to your connections list. I also got rid of the connection array inside the user table and created a new table for that to make it easier to add connections. Created a card for the connection view and created a function to add connections to a user.

**Comment by NatalmanNahm** [comment]
I also added an auto Scrolling to the messageView all the way to the last message when it first appears, and when you send a message/or receive one!

**Comment by AricaLConrad** [comment]
Thanks for all your work on this issue. This message functionality is quite cool!

**Comment by NatalmanNahm** [comment]
Thank You!

**Pull request merged**
